server:
  port: 8081
spring:
  application:
    name: creation
  datasource:
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  redis:
    host: 101.43.251.185
    #Redis服务器连接端口
    port: 6379
    #Redis服务器连接密码（默认为空）
    password: yty123456
    #连接超时时间（毫秒）
    timeout: 3000
    pool:
      #连接池最大连接数（使用负值表示没有限制）
      max-active: 300
      #连接池最大阻塞等待时间（使用负值表示没有限制0.）
      max-wait: 1000
      #连接池中的最大空闲连接
      max-idle: 100
      #连接池中的最小空闲连接
      min-idle: 50

mybatis-plus:
#  configuration:
#      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: is_deleted # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
#
#logging:
#  config: classpath:logback-spring.xml
#  level:
#    dao: debug
#    org:
#      mybatis: debug
